name: Update Covers & Blacklist Index

on:
  workflow_run:
    workflows: ["Update PSN™ Database"]
    types:
      - completed
  push:
    paths:
      - 'resources/covers/compressed/**'
      - 'resources/database/official/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout PSN-Content
        uses: actions/checkout@v3
        with:
          path: PSN-Content

      - name: Checkout Recently-Played-Games (Repositório de Hashes)
        uses: actions/checkout@v3
        with:
          repository: PS3-Pro/Recently-Played-Games
          path: Recently-Played-Games

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate Indexes & Blacklist
        run: |
          cd PSN-Content
          ls -1 resources/covers/compressed/*.JPG | awk -F'/' '{print $NF}' | sed 's/\.JPG//g' > resources/covers/index.tsv
          
          node .github/scripts/generate_blacklist.js

      - name: Commit and Push
        run: |
          cd PSN-Content
          git config --global user.name "PS3-Pro Bot"
          git config --global user.email "bot@ps3pro.com"
          git add resources/covers/index.tsv resources/covers/blacklist.tsv
          git commit -m "Auto-update: Covers and Blacklist indexes" || echo "No changes to commit"
          git push