name: Update PSN™ Database

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Sync NPS and Detect Changes
        run: |
          BASE_DIR="resources/database/official"
          LATEST_DIR="resources/database/latest"
          PY_SCRIPT=".github/scripts/update_latest.py"
          
          mkdir -p "$BASE_DIR/pending"
          mkdir -p "$LATEST_DIR"

          categories=("games" "avatars" "demos" "dlcs" "themes")

          for cat in "${categories[@]}"; do
            echo "Processando $cat..."
            
            URL_OFFICIAL="https://nopaystation.com/tsv/PS3_${cat^^}.tsv"
            curl -L "$URL_OFFICIAL" -o "nps_raw.tsv"
            
            awk -F'\t' 'NR==1 || ($4 != "MISSING" && $4 != "")' "nps_raw.tsv" > "nps_clean.tsv"
            
            python "$PY_SCRIPT" "$BASE_DIR/${cat}.tsv" "nps_clean.tsv" "$LATEST_DIR/latest_${cat}.tsv"
            
            mv "nps_clean.tsv" "$BASE_DIR/${cat}.tsv"
            rm "nps_raw.tsv"

            curl -L "https://nopaystation.com/tsv/pending/PS3_${cat^^}.tsv" -o "p_raw.tsv"
            awk -F'\t' 'NR==1 || ($4 != "MISSING" && $4 != "")' "p_raw.tsv" > "p_clean.tsv"
            
            python "$PY_SCRIPT" "$BASE_DIR/pending/${cat}.tsv" "p_clean.tsv" "$LATEST_DIR/latest_${cat}.tsv"
            mv "p_clean.tsv" "$BASE_DIR/pending/${cat}.tsv"
            rm "p_raw.tsv"
          done

      - name: Commit and Push changes
        run: |
          git config --global user.name "PS3-Pro Bot"
          git config --global user.email "bot@ps3pro.com"
          
          git add resources/database/official/*.tsv
          git add resources/database/official/pending/*.tsv
          git add resources/database/latest/*.tsv
          
          # Só faz o commit se houver mudança real nos arquivos
          git diff-index --quiet HEAD || git commit -m "Auto-update: Synchronized with NoPayStation (Official & Pending)"
          git push